version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
    ports:
      - "5433:5432"

  fcl_sw:
    image: fcl_sw:latest
    restart: always
    container_name: myContainer
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:Aa123456@postgres:5432/mydatabase?connect_timeout=300
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile